version:  2

models:
    -  name: stg_customer
       description: "Holds customer information"
       columns:
          - name: customer_unique_id
            tests:
                -  not_null

    -  name: stg_orders
       description: "Holds customer  order information"
       columns: 
          - name: customer_order_id
            tests: 
                - unique
                - not_null

    -  name:  stg_state
       description: "Holds state info"
       columns:
            - name: st
              tests:
                - accepted_values:
                    values:
                        [
                        "AC",
                        "AL",
                        "AP",
                        "AM",
                        "BA",
                        "CE",
                        "DF",
                        "ES",
                        "GO",
                        "MA",
                        "MT",
                        "MS",
                        "MG",
                        "PA",
                        "PB",
                        "PR",
                        "PE",
                        "PI",
                        "RJ",
                        "RN",
                        "RS",
                        "RO",
                        "RR",
                        "SC",
                        "SP",
                        "SE",
                        "TO",
                        ]